call pathogen#infect()

syntax on
colorscheme resistor
filetype indent plugin on

" Windows
" ============================================================================
set splitbelow splitright
set equalalways
set winminheight=0
set winminwidth=0

set spelllang=en_us

let mapleader = ","
let maplocalleader = ","

:noremap <leader>v :vsp<CR>:enew<CR>:pwd<CR>
:noremap <leader>s :split<CR>:enew<CR>:pwd<CR>
:noremap <leader>l <C-w>l
:noremap <leader>h <C-w>h
:noremap <leader>j <C-w>j
:noremap <leader>k <C-w>k
:noremap <leader>- <C-W>_
:noremap <leader>N <C-W>n<C-W>_
:noremap <leader>? <C-W>n<C-W>H<C-W>q
:noremap <leader>c :only<CR>:tabonly<CR>
:noremap J <Esc><C-w>j<C-w>_
:noremap K <Esc><C-w>k<C-w>_
:noremap <leader>r :! make %<CR>
:noremap <leader>R :! jshint %<CR>
:noremap <leader>/ <C-W>n<C-W>H<C-W>q<C-W>t<C-W>_<C-W>l<C-W>_<C-W>l<C-W>_<C-W>l<C-W>_
:noremap <leader>n :NERDTreeToggle<CR>

:noremap <leader>b :CtrlPBuffer<CR>

:noremap <leader>gst :!tig status<CR>
:noremap <leader>gpr :!git pull --rebase<CR>
:noremap <leader>gup :!git pull<CR>
:noremap <leader>gush :!git push<CR>

:noremap <C-c> <ESC>
:noremap <C-w><C-c> <ESC>
:noremap <C-w>c <ESC>

" Tabs
" ============================================================================
set expandtab
set softtabstop=4
set shiftwidth=4
set tabstop=4
set smarttab
set autoindent
set textwidth=0
set showtabline=2
set laststatus=1

" Searching
" ============================================================================
set hlsearch   " highlight search
set incsearch  " incremental search, search as you type
set ignorecase " Ignore case when searching
set smartcase  " Ignore case when searching lowercase

" Directories
" ============================================================================
" Setup backup location and enable
set backupdir=~/.backup/vim
set backup

" Set Swap directory
set directory=~/.backup/vim/swap

" Change file completion to mimic shell behavior
set wildmenu
set wildmode=list:longest
set wildignore+=*/tmp/*,*/.gs/*,*.DS_Store,*.rdb,*.aof,*.sqlite3,*.pid

" Inser New Line
" ============================================================================
:noremap <S-Enter> O<ESC>
:noremap <Enter> o<ESC>

" Set encodings to UTF8
" ============================================================================
set encoding=utf-8
set fileencoding=utf-8

" set list listchars=tab:>-,trail:.,extends:>

" Allow backspace to work on auto indents, EOL, or start of lines.
set backspace=indent,eol,start

" Change mapping of CtrlP
let g:ctrlp_map = '<leader>t'
let g:ctrlp_custom_ignore = '\v[\/](\.git|node_modules)$'

" Status line
set laststatus=2      " always show it
set statusline=%f     " tail only filename from path
set statusline+=%h    " help file flag
set statusline+=%m    " modified flag
set statusline+=%r    " read only flag
set statusline+=%=    " left/right separator
set statusline+=%c,   " cursor column
set statusline+=%l/%L " cursor line/total lines
set statusline+=\ %P  " percent through file

" Copy Paste
nmap <F1> :set paste<CR>:r !pbpaste<CR>:set nopaste<CR>
imap <F1> <Esc>:set paste<CR>:r !pbpaste<CR>:set nopaste<CR>
nmap <F2> :.w !pbcopy<CR><CR>
vmap <F2> :w !pbcopy<CR><CR>

" EasyAlign
" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
