call pathogen#infect() "Use Pathogen for turning on bundles

syntax on                   "syntax highlighting
colorscheme codeschool
filetype plugin indent on   "turn on filetype detection

set spelllang=en_us
set encoding=utf-8
set fileencoding=utf-8
set number              "This turns on line numbering
:highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE
set backspace=indent,eol,start " allow backpace to work on auto indents, EOL, and start of lines

let mapleader = ","        "comma is the leader key
let maplocalleader = ","   "comma is the leader key

" Window/Pane settings
set splitbelow splitright
set equalalways
set winminheight=0
set winminwidth=0

" Pane navigation
:noremap <leader>v :vsp<CR>
:noremap <leader>l <C-w>l
:noremap <leader>h <C-w>h
:noremap <leader>k <C-w>k
:noremap <leader>j <C-w>j
:noremap <leader>c :only<CR>:tabonly
:noremap <leader>N <C-W>n<C-W>_

"Git/Tig Mappings
:noremap <leader>gst :!tig status<CR>
:noremap <leader>gup :!git pull<CR>
:noremap <leader>gush :!git push<CR>

"Tab Settings
set expandtab "tabs are expanded into spaces
set softtabstop=4
set shiftwidth=4
set tabstop=4
set smarttab " tabs will use shiftwidth and tab to proper indents
set textwidth=0

"Searching
set hlsearch    " highlight search
set incsearch   " search as you type
set ignorecase  " ignore case when search
set smartcase   " ignore case when search lowercase

"Back up directory
set backupdir=~/.backup/vim
set backup

"Swap Directory
set directory=~/.backup/vim/swap

"Change file completeion to mimic shell behavior
set wildmenu
set wildmode=list:longest

" Status line
set laststatus=2

" Highlight trailing space
:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/

" Nerd Tree
:noremap <leader>n :NERDTreeToggle<CR>

" Change mapping of CtrlP
let g:ctrlp_map = '<leader>t'
let g:ctrlp_custom_ignore = '\v[\/](\.git|node_modules)$'
:noremap <leader>b :CtrlPBuffer<CR>

" Paste toggle
set pastetoggle=<leader>p

" Fixes syntax highlight for vue files
autocmd FileType vue syntax sync fromstart
